# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy To Firebase

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run-script build
    - name: Archive Production artifact
      uses: actions/upload-artifact@master
      with:
       name: build
       path: build
       
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Repo
       uses: actions/checkout@master
     - name: Downlaod Artifact
       uses: w9jds/firebase-action@master
       with:
         args: deploy --only hosting
       env:
        FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
